#!/usr/bin/env python3
"""Contains a coroutine that collects numbers yielded by asyncgenerator."""
from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Use list comprehension to return list of random numbers.

    :return: list of random numbers generated by async_generator
    :rtype: List[float]
    """
    return [_ async for _ in async_generator()]
